apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: <+service.name>-<+project.name>
spec:
  template:
    spec:
      containers:
        - image: <+artifact.image>
          ports:
            - containerPort: 5100
